In [140]:
import tensorflow as tf
import numpy as np

# Tensor Dimensions

In [141]:
tensor_zero_d = tf.constant(4) #0 d tensor
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [142]:
tensor_one_d = tf.constant([2,0,-1], dtype = tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.int64)
bool_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)
print(bool_tensor_one_d)

tf.Tensor([ 2.  0. -1.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -1], shape=(3,), dtype=int64)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [143]:
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [144]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [145]:
tensor_three_d = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])
print(tensor_three_d.shape)
tensor_three_d_2 = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])
print(tensor_three_d_2.ndim)

(2, 3, 3)
3


In [146]:
print(tensor_three_d.ndim) # Dimension of our tensor

3


# 4D Tensor are 3D tensors stacked 

In [147]:
tensor_four_d = tf.constant([[[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]]
                             ,
                             [[[15,24,35],
                             [25,33,41],
                             [45,66,73]],

                             [[16,26,37],
                             [28,39,40],
                             [54,65,78]]]
                             ])
print(tensor_four_d.ndim)
print(tensor_four_d.shape)

4
(2, 2, 3, 3)


In [148]:
tf_string = tf.constant(['hello world', 'hi'])

## Convert a numpy array to a tensor

In [149]:
import numpy as np
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [150]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


## Eye Tensor

In [151]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=[2,2],
    dtype=tf.dtypes.int32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]


 [[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]], shape=(2, 2, 3, 3), dtype=int32)


In [152]:
print(3 * eye_tensor)

tf.Tensor(
[[[[3 0 0]
   [0 3 0]
   [0 0 3]]

  [[3 0 0]
   [0 3 0]
   [0 0 3]]]


 [[[3 0 0]
   [0 3 0]
   [0 0 3]]

  [[3 0 0]
   [0 3 0]
   [0 0 3]]]], shape=(2, 2, 3, 3), dtype=int32)


## tf.fill

In [153]:
fill_tensor = tf.fill([2,3,4],5)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


# tf.ones

In [154]:
ones_tensor = tf.ones([2,2,2])
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [155]:
ones_like = tf.ones_like(fill_tensor)
print(ones_like)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


In [156]:
zeros_tensor = tf.zeros([3,2])
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [157]:
print(tf.shape(tensor_three_d)) #returns a shape tensor of the input tensor

tf.Tensor([2 3 3], shape=(3,), dtype=int32)


In [158]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [159]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t, out_type = tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [160]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[100.08422   99.1391  ]
 [100.37812   99.994804]
 [ 99.50547  100.61782 ]], shape=(3, 2), dtype=float32)


In [161]:
tf.random.uniform(
    [5,5],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.13678  , 62.85462  ,  1.7384648, 34.31449  , 51.063763 ],
       [37.77541  ,  7.321596 ,  2.1370292, 28.717709 , 47.10616  ],
       [69.36141  ,  7.321334 , 93.251205 , 20.843052 , 70.10583  ],
       [45.85639  , 85.962616 , 92.93433  , 20.291912 , 76.86551  ],
       [60.016026 , 27.039742 , 88.18061  ,  5.365038 , 42.274464 ]],
      dtype=float32)>

# tensor indexing

In [162]:
tensor_indexed = tf.constant([99,10,9,92,6,4,34,62,56])
print(tensor_indexed[0:4])
print(tensor_indexed[1:6])
print(tensor_indexed[1:6:2])

tf.Tensor([99 10  9 92], shape=(4,), dtype=int32)
tf.Tensor([10  9 92  6  4], shape=(5,), dtype=int32)
tf.Tensor([10 92  4], shape=(3,), dtype=int32)


In [163]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

# Indexing Dim. > 2

In [164]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]])

print(tensor_two_d[0:3,0:2]) #for rows, for columns
print(tensor_two_d[0:3,:]) # all columns
print(tensor_two_d[2]) #the whole of the third row
print(tensor_two_d[:,1])
print(tensor_two_d[...,1]) #all rows of the 2nd column 

tf.Tensor(
[[1 2]
 [2 3]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)
tf.Tensor([5 6 7], shape=(3,), dtype=int32)
tf.Tensor([2 3 6], shape=(3,), dtype=int32)
tf.Tensor([2 3 6], shape=(3,), dtype=int32)


In [165]:
tensor_three_d = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])

print(tensor_three_d[0,:,:])
print(tensor_three_d[0,0,:])
print(tensor_three_d[0,:,-1])
print(tensor_three_d[0:2,:,-1])
print(tensor_three_d[...,:,1])



tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([3 4 7], shape=(3,), dtype=int32)
tf.Tensor(
[[3 4 7]
 [3 4 7]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 3 6]
 [2 3 6]], shape=(2, 3), dtype=int32)


# Math Operations

In [166]:
x = tf.constant([-2.25, 3.25])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [167]:
# complex number
x_abs_complex = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [168]:
x = tf.constant([1, 2], dtype=tf.int8)
y = tf.constant([3, 0], dtype=tf.int8)
print(tf.add(x,y))
print(tf.multiply(x,y))
print(tf.subtract(x,y))
print(tf.math.divide_no_nan(x,y)) #gives 0. when divide by 0

tf.Tensor([4 2], shape=(2,), dtype=int8)
tf.Tensor([3 0], shape=(2,), dtype=int8)
tf.Tensor([-2  2], shape=(2,), dtype=int8)
tf.Tensor([0.33333334 0.        ], shape=(2,), dtype=float32)


In [169]:
x2 = tf.constant([[1, 2], [3,4]], dtype=tf.int8)
x3 = x2 = tf.constant([1, 2], dtype=tf.int8)
y2 = tf.constant([3], dtype=tf.int8) #this tensor is broadcasted
y3 = tf.constant([[3], [6], [9]], dtype=tf.int8)
print(tf.add(x2,y2))
print(tf.math.multiply(x2, y3))

tf.Tensor([4 5], shape=(2,), dtype=int8)
tf.Tensor(
[[ 3  6]
 [ 6 12]
 [ 9 18]], shape=(3, 2), dtype=int8)


In [170]:
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-2., 0., 2., 5.])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [171]:
x_argmax1 = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
print(x_argmax1.shape)
print(tf.math.argmax(x_argmax1, 0)) #returns the index of the maximum value in a row
#comparision is done on each row for the same column
print(tf.math.argmin(x_argmax1, 1))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [172]:
x_argmax2 = tf.constant([2, 20, 30, 3, 6])
print(tf.math.argmax(x_argmax2))


tf.Tensor(2, shape=(), dtype=int64)


In [173]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [174]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [175]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]], dtype = tf.float16)
print(tf.math.reduce_sum(tensor_two_d, axis=None, keepdims=False, name=None)) #summing all the elements in the tensor
print(tf.math.reduce_sum(tensor_two_d, axis=0, keepdims=False, name=None)) #fix the row and add the columns
print(tf.math.reduce_mean(tensor_two_d, axis=0, keepdims=False, name=None))
print(tf.math.reduce_std(tensor_two_d, axis=0, keepdims=True, name=None))

tf.Tensor(33.0, shape=(), dtype=float16)
tf.Tensor([ 8. 11. 14.], shape=(3,), dtype=float16)
tf.Tensor([2.666 3.666 4.668], shape=(3,), dtype=float16)
tf.Tensor([[1.7   1.7   1.699]], shape=(1, 3), dtype=float16)


In [176]:
tf.math.top_k(tensor_two_d) #first part 

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=float16, numpy=
array([[3.],
       [4.],
       [7.]], dtype=float16)>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [2],
       [2]], dtype=int32)>)

# Linear Algebra operations

In [177]:
x_1 = tf.constant([[1,2,0], [3,5,-1]])
x_2 = tf.constant([[3,4],[7,2],[9,2]]) 

tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17,  8],
       [35, 20]], dtype=int32)>

In [178]:
print(x_1@x_2) # '@' means matrix multiplication, '*' means element wise multiplication

tf.Tensor(
[[17  8]
 [35 20]], shape=(2, 2), dtype=int32)


In [179]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  5],
       [ 0, -1]], dtype=int32)>

In [180]:
x_1 = tf.constant([[[1,2],
                    [2,3]],

                    [[4,5],
                    [6,8]],

                    [[1,2],
                    [2,3]]
                    ])

x_2 = tf.constant([[[1,2],
                    [2,3]],

                    [[1,2],
                    [2,3]],

                    [[4,5],
                     [6,8]]])
print(x_1.shape, x_2.shape)
print(tf.linalg.matmul(x_1, x_2))

(3, 2, 2) (3, 2, 2)
tf.Tensor(
[[[ 5  8]
  [ 8 13]]

 [[14 23]
  [22 36]]

 [[16 21]
  [26 34]]], shape=(3, 2, 2), dtype=int32)


In [181]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]], dtype = tf.int32)

print(tf.linalg.band_part( tensor_two_d, 0, -1, name=None))

tf.Tensor(
[[1 2 3]
 [0 3 4]
 [0 0 7]], shape=(3, 3), dtype=int32)


In [182]:
tensor_two_d_inv = tf.constant([[1,2,3],
                            [2,3,4],
                            [5,6,7]], dtype = tf.float32)
tf.linalg.inv(tensor_two_d_inv) #inverse only works for square matrices

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ -6291460. ,   8388611. ,  -2097152. ],
       [ 12582914. , -16777218. ,   4194304. ],
       [ -6291455.5,   8388608. ,  -2097152. ]], dtype=float32)>

In [183]:
tensor_two_d_inv = tf.constant([[1,2,3],
                            [2,3,4],
                            [5,6,7]], dtype = tf.int32)
tensor_two_d@tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[20, 26, 32],
       [28, 37, 46],
       [52, 70, 88]], dtype=int32)>

In [184]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]], dtype = tf.float32)
s,u,v = tf.linalg.svd(tensor_two_d)
print(s)
print(u)
print(v)

tf.Tensor([1.2327755e+01 1.0131612e+00 2.0643913e-07], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.29715562 -0.7520271  -0.5883485 ]
 [ 0.43532172 -0.44171327  0.7844646 ]
 [ 0.84982     0.4892288  -0.1961161 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.43940678  0.80015934  0.40824848]
 [ 0.5677593   0.10479952 -0.81649655]
 [ 0.69611144 -0.590561    0.4082481 ]], shape=(3, 3), dtype=float32)


# EinSum Operator

In [185]:
A = np.array([[2,6,5,2], 
              [9,6,4,0],
              [4,7,4,8]])

B = np.array([[2,9,0,3,0],
              [4,5,2,1,4],
              [1,2,5,6,3],
              [5,7,3,5,2]])

print(A.shape, B.shape)
print(np.einsum('ij,jk -> ik', A,B))

(3, 4) (4, 5)
[[ 43  72  43  52  43]
 [ 46 119  32  57  36]
 [ 80 135  58  83  56]]


In [186]:
A = np.array([[2,6,5,2], 
              [9,6,4,0],
              [4,7,4,8]])

B = np.array([[2,9,0,3],
              [4,5,2,1],
              [1,2,5,6]])

print(A.shape, B.shape)
print(np.einsum('ij,ij -> ij', A,B)) #matrix element wise multiplication

(3, 4) (3, 4)
[[ 4 54  0  6]
 [36 30  8  0]
 [ 4 14 20 48]]


In [187]:
A = np.array([[2,6,5,2], 
              [9,6,4,0],
              [4,7,4,8]])
print(np.einsum('ij -> ji', A)) #getting the transpose


[[2 9 4]
 [6 6 7]
 [5 4 4]
 [2 0 8]]


In [188]:
A = tf.constant([[[1,2,3],
                [2,3,4],
                [5,6,7]],

                [[1,2,3],
                [2,3,4],
                [5,6,7]]])

B = tf.constant([[[1,2,3],
                [2,3,4],
                [5,6,7]],

                [[1,2,3],
                [2,3,4],
                [5,6,7]]])

print(np.einsum('bij,bjk -> bik', A,B)) # this is matrix multiplication

[[[20 26 32]
  [28 37 46]
  [52 70 88]]

 [[20 26 32]
  [28 37 46]
  [52 70 88]]]


In [189]:
A = tf.constant([[[1,2,3],
                [2,3,4],
                [5,6,7]],

                [[1,2,3],
                [2,3,4],
                [5,6,7]]])

print(np.sum(A))
print(np.einsum('bij ->', A)) # no output mean that we are summing up all the possible values

66
66


In [190]:
A = np.array([[2,6,5,2], 
              [9,6,4,0],
              [4,7,4,8]])
print(np.sum(A, axis = 1)) # sum across columns
print(np.einsum('ij->j', A))
print('_______')
print(np.einsum('ij->i', A))


[15 19 23]
[15 19 13 10]
_______
[15 19 23]


# In the paper 'Attention is all you need'

In [191]:
Q = np.random.randn(32,64,512) #bqm
K = np.random.randn(32,128,512) #bkm

print(np.einsum('bqm, bkm -> bqk', Q,K))
print(np.einsum('bqm, bkm -> bqk', Q,K).shape)

[[[-1.09843450e+01 -2.94041795e+01 -8.09227111e-01 ...  2.73589687e+01
   -1.00483133e+01 -1.63516929e+01]
  [ 3.45340034e+00  3.89980000e+01  1.50848530e+01 ...  2.86806512e+01
    1.45252591e+00  3.83748933e+01]
  [ 4.97711657e-01  1.95229703e+01  1.40115075e+00 ... -2.40510974e+01
   -1.30223725e+01 -3.03807240e+00]
  ...
  [ 2.73589192e+01  2.23930092e-01  3.71775632e+00 ... -3.29526316e-01
    2.46265347e+01 -4.80809487e+01]
  [-1.21726530e+01  4.01372783e+00 -1.40719269e+01 ...  2.15692328e+01
   -1.45445317e+01  5.74218579e+00]
  [-2.85550895e+01 -5.78876458e+00  1.42395887e+01 ... -2.17462321e+01
    1.07675936e+01  3.69406336e+00]]

 [[-1.49645089e+01 -7.05155201e+00  3.72525664e+01 ...  1.16488043e+01
   -3.13319833e+01  2.32250625e+01]
  [-4.30168557e+01 -1.09305088e+01  1.93765436e+00 ...  4.57481605e+01
    3.33985516e+01  3.55620534e+01]
  [ 3.29574853e+01  4.57070151e+01 -3.86993000e+01 ...  1.75855541e+01
   -3.86273379e+00  1.25413867e+01]
  ...
  [-2.67643609e+01 -1.6

# In the paper 'Reformer'

In [192]:
A = np.random.randn(2,4,4,2) #bcij
B = np.random.rand(2,4,4,1) #bcik
print(np.einsum('bcik,bcij -> bckj', B,A))


[[[[-1.21338508 -0.11515789]]

  [[-1.18171059  0.00695166]]

  [[-1.93920314 -1.2159339 ]]

  [[-0.69975916  0.0055152 ]]]


 [[[ 1.00191671 -0.02858821]]

  [[ 0.5793755  -2.10470567]]

  [[ 1.26864152 -1.15210267]]

  [[-0.68297164  0.55576235]]]]


# Common Tensor functions

In [193]:
tf.random.set_seed(42)
tensor_three_d = tf.random.uniform(
    shape=[4,2,3], 
    minval=0, 
    maxval=10, 
    dtype=tf.int32
)
print(tensor_three_d)

tf.Tensor(
[[[7 9 1]
  [6 2 4]]

 [[3 3 1]
  [1 2 0]]

 [[1 1 0]
  [8 9 2]]

 [[9 9 1]
  [2 7 4]]], shape=(4, 2, 3), dtype=int32)


In [194]:
print(tf.expand_dims(tensor_three_d, axis = 0).shape) #added a dimension

(1, 4, 2, 3)


In [195]:
x = tf.constant([1,2,3])
print(x.shape)
print(tf.expand_dims(x, axis = 0)) #added a dimension, dim added to the 0th index
print(tf.expand_dims(x, axis = 1)) # dim added ot the 1st index

(3,)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [196]:
x = tf.constant([[1,2,3]])
print(x.shape)
print(tf.squeeze(x).shape)

(1, 3)
(3,)


In [197]:
tensor_three_d = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])
print(tensor_three_d.shape)
tensor_three_d = tf.expand_dims(tensor_three_d, axis = 3)
print(tensor_three_d.shape)
print(tf.reshape(tensor_three_d, [2,3,3]).shape) #reshaped to the desired shape by removing the 1 at the end


(2, 3, 3)
(2, 3, 3, 1)
(2, 3, 3)


In [198]:
x_reshape = tf.constant([[1,2,3],
                        [4,5,6]])

print(tf.reshape(x_reshape, [6])) #reshape tensor needs to have the same number of elements as the original tensor
print(tf.reshape(x_reshape, [3,2]))
print(tf.reshape(x_reshape, [2,-1])) # '-1': tf automatically knows what the 2nd index needs to be
print(tf.reshape(x_reshape, [-1]))



tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [199]:
t1 = [[1, 2, 3],
       [4, 5, 6]]

t2 = [[7, 8, 9],
       [10, 11, 12]]
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

print(tf.concat([t1, t2], axis = 0))
print(tf.concat([t1, t2], axis = 1))

(2, 3)
(2, 3)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [200]:
t1 = [[[1, 2, 3],
       [4, 5, 6]]]

t2 = [[[7, 8, 9],
       [10, 11, 12]]]

print(tf.concat([t1,t2], axis = 0))
print(tf.concat([t1,t2], axis = 1))
print(tf.concat([t1,t2], axis = 2))

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]], shape=(1, 4, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3  7  8  9]
  [ 4  5  6 10 11 12]]], shape=(1, 2, 6), dtype=int32)


In [201]:
print(tf.stack([t1,t2], axis = 0)) # creates an extra axis
print(tf.stack([t1,t2], axis = 1))

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]]


 [[[ 7  8  9]
   [10 11 12]]]], shape=(2, 1, 2, 3), dtype=int32)
tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]], shape=(1, 2, 2, 3), dtype=int32)


# Padding

In [202]:
t = tf.constant([[1, 2, 3],
                [4, 5, 6]])
paddings = tf.constant([[1, 1], [2, 2]]) #1 row above the 1 row below, 2 columns to the left and 2 columns to the right
# 'constant_values' is 0.
# rank of 't' is 2.
tf.pad(t, paddings, "CONSTANT", constant_values=0)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [203]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(tf.gather(params, [1,2,3])) #like indexing
print(tf.gather(params, tf.range(1,4)))
print(tf.gather(params, [0,3,5]))

tf.Tensor([b'p1' b'p2' b'p3'], shape=(3,), dtype=string)
tf.Tensor([b'p1' b'p2' b'p3'], shape=(3,), dtype=string)
tf.Tensor([b'p0' b'p3' b'p5'], shape=(3,), dtype=string)


In [204]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]])

print(tf.gather(tensor_two_d, [0,2], axis = 0))
print(tf.gather(tensor_two_d, [0,2], axis = 0))

tf.Tensor(
[[1 2 3]
 [5 6 7]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [5 6 7]], shape=(2, 3), dtype=int32)


In [205]:
tensor_two_d = tf.constant([
                            [[1,2,3],
                            [2,3,4],
                            [5,6,7]]
                            ])
print(tensor_two_d.shape)
print(tf.gather(tensor_two_d, [0,2], axis = 1)) # Look that the index in the shape

(1, 3, 3)
tf.Tensor(
[[[1 2 3]
  [5 6 7]]], shape=(1, 2, 3), dtype=int32)


In [206]:
tensor_two_d = tf.constant([
                            [[1,2,3],
                            [2,3,4],
                            [5,6,7]],

                            [[3,24,53],
                            [24,33,45],
                            [56,67,47]]
                            ])

print(tensor_two_d.shape)
print(tf.gather(tensor_two_d, [0], axis = 0))
print(tf.gather(tensor_two_d, [0,2], axis = 1)) # gives the 0th and 2nd element of both the batches

(2, 3, 3)
tf.Tensor(
[[[1 2 3]
  [2 3 4]
  [5 6 7]]], shape=(1, 3, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 5  6  7]]

 [[ 3 24 53]
  [56 67 47]]], shape=(2, 2, 3), dtype=int32)


In [207]:
indices = [[1]],
params = [['a', 'b', 'c'], 
          ['d', 'e', 'f']]

print(tf.gather_nd(params, indices))

indices = [[1,2]]
print(tf.gather_nd(params, indices))

indices = [[0],[1]]
print(tf.gather_nd(params, indices))


tf.Tensor([[[b'd' b'e' b'f']]], shape=(1, 1, 3), dtype=string)
tf.Tensor([b'f'], shape=(1,), dtype=string)
tf.Tensor(
[[b'a' b'b' b'c']
 [b'd' b'e' b'f']], shape=(2, 3), dtype=string)


In [208]:
indices = [[0,1],[1,1]]
params = [
            [['a0', 'b0'],
            ['c0', 'd0']
            ],

            [['a1', 'b1'],
            ['c1', 'd1']
            ]
        ]
print(tf.gather_nd(params, indices)) #take the 0th element and it's 1st index
indices = [[0,1,0]] #0th element then the 1st row and then the 0th column
print(tf.gather_nd(params, indices))

tf.Tensor(
[[b'c0' b'd0']
 [b'c1' b'd1']], shape=(2, 2), dtype=string)
tf.Tensor([b'c0'], shape=(1,), dtype=string)


In [209]:
indices = [[[0, 1], 
            [1, 0]], 

            [[0, 0], 
             [1, 1]]]
 
params = [[['a0', 'b0'], 
           ['c0', 'd0']],

            [['a1', 'b1'], 
             ['c1', 'd1']]]

print(tf.gather_nd(params, indices))

tf.Tensor(
[[[b'c0' b'd0']
  [b'a1' b'b1']]

 [[b'a0' b'b0']
  [b'c1' b'd1']]], shape=(2, 2, 2), dtype=string)


In [210]:
indices = [[0, 1], 
            [1, 0]]

params = [[['a0', 'b0'], 
           ['c0', 'd0']],

            [['a1', 'b1'], 
            ['c1', 'd1']]]

print(tf.gather_nd(params, indices, batch_dims=1)) #batchdims = 1 means that it is batch aware
# Notice that the indices list is 2D and it's 0th element corresponds to the 0th batch of params and the 1st element corresponds to the 1st batch of params

tf.Tensor([b'b0' b'c1'], shape=(2,), dtype=string)


# Ragged Tensors

In [218]:
'''tf.constant([
                [[1,2,3],
                [2,3,4],
                [5,6,7]]
                ])'''
# OKAY Tensor ^


# RAGGED Tensor & Non Rectangular
'''tf.constant([
                [[1],
                [2,3],
                [5,6,7]]
                ])'''

tensor_two_d = [[1],
                [2,3],
                [5,6,7],
                [9,11]] # Notice there is no tf.constant in the beginning
                

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)
print(tensor_ragged)

(4, None)
<tf.RaggedTensor [[1], [2, 3], [5, 6, 7], [9, 11]]>


In [ ]:
T, F = (True, False)
data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mask1=[[T, F, T], [F, F, F], [T, F, F]]

print(tf.ragged.boolean_mask(data, mask1))

mask2=[T, F, F]
print(tf.ragged.boolean_mask(data, mask2))

<tf.RaggedTensor [[1, 3], [], [7]]>
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [226]:
values=[3, 1, 4, 1, 5, 9, 2, 6]
row_lengths=[0, 4, 3, 1, 0] # 0th row has 0 elements, 

print(tf.RaggedTensor.from_row_lengths(values, row_lengths))

<tf.RaggedTensor [[], [3, 1, 4, 1], [5, 9, 2], [6], []]>


# Sparse Tensors

In [ ]:
tensor_sparse = tf.sparse.SparseTensor(indices=[[1, 2], [3,3]], values=[99, 36], dense_shape=[5,6]) # want 99 at pos(1,2) and 36 at pos(3,3) in a (5,6) tensor.
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0, 99,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 36,  0,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

# String Tensors

In [235]:
tensor_string = tf.constant(['Hello', 'I', 'am', 'a', 'string'])
print(tensor_string)

tf.Tensor([b'Hello' b'I' b'am' b'a' b'string'], shape=(5,), dtype=string)


In [239]:
print(tf.strings.join(tensor_string, separator = ' '))
print(tf.strings.join(tensor_string, separator = '+'))

tf.Tensor(b'Hello I am a string', shape=(), dtype=string)
tf.Tensor(b'Hello+I+am+a+string', shape=(), dtype=string)


# Variables

In [248]:
x = tf.constant([5,6,7])
x_var = tf.Variable(x, name='var1')
print(x_var)

<tf.Variable 'var1:0' shape=(3,) dtype=int32, numpy=array([5, 6, 7], dtype=int32)>


In [249]:
x_var.assign_sub([3,1,2]) #5-3, 6-1, 7-2
print(x_var)

<tf.Variable 'var1:0' shape=(3,) dtype=int32, numpy=array([2, 5, 5], dtype=int32)>


In [250]:
x_var.assign_add([2,4,1])
print(x_var)

<tf.Variable 'var1:0' shape=(3,) dtype=int32, numpy=array([4, 9, 6], dtype=int32)>


In [253]:
with tf.device('CPU:0'):
    x_var = tf.Variable(0.2)
    x_tensor = tf.constant([0.2, 0.3])
print(x_var.device)
print(x_tensor)
print(x_tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([0.2 0.3], shape=(2,), dtype=float32)
/job:localhost/replica:0/task:0/device:CPU:0


# Trick to run computation faster

In [ ]:
with tf.device('CPU:0'):
    x_1 = tf.constant([3,8])
    x_2 = tf.Variable([1]) # will be broadcasted

with tf.device('GPU:0'): # I think the CPU is being printed when done x_3.device because CPU is global
    x_3 = x_1 + x_2

print(x_3)

tf.Tensor([4 9], shape=(2,), dtype=int32)


In [ ]:
print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device) # I think the CPU is being printed when done x_3.device because CPU is global

tf.Tensor([3 8], shape=(2,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([1], dtype=int32)> /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([4 9], shape=(2,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
