In [2]:
import tensorflow as tf
import numpy as np

# Tensor Dimensions

In [3]:
tensor_zero_d = tf.constant(4) #0 d tensor
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2,0,-1], dtype = tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.int64)
bool_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)
print(bool_tensor_one_d)

tf.Tensor([ 2.  0. -1.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -1], shape=(3,), dtype=int64)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [5]:
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [6]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [7]:
tensor_three_d = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])
print(tensor_three_d.shape)
tensor_three_d_2 = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])
print(tensor_three_d_2.ndim)

(2, 3, 3)
3


In [8]:
print(tensor_three_d.ndim) # Dimension of our tensor

3


# 4D Tensor are 3D tensors stacked 

In [9]:
tensor_four_d = tf.constant([[[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]]
                             ,
                             [[[15,24,35],
                             [25,33,41],
                             [45,66,73]],

                             [[16,26,37],
                             [28,39,40],
                             [54,65,78]]]
                             ])
print(tensor_four_d.ndim)
print(tensor_four_d.shape)

4
(2, 2, 3, 3)


In [10]:
tf_string = tf.constant(['hello world', 'hi'])

## Convert a numpy array to a tensor

In [11]:
import numpy as np
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [12]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


## Eye Tensor

In [13]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=[2,2],
    dtype=tf.dtypes.int32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]


 [[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]], shape=(2, 2, 3, 3), dtype=int32)


In [14]:
print(3 * eye_tensor)

tf.Tensor(
[[[[3 0 0]
   [0 3 0]
   [0 0 3]]

  [[3 0 0]
   [0 3 0]
   [0 0 3]]]


 [[[3 0 0]
   [0 3 0]
   [0 0 3]]

  [[3 0 0]
   [0 3 0]
   [0 0 3]]]], shape=(2, 2, 3, 3), dtype=int32)


## tf.fill

In [15]:
fill_tensor = tf.fill([2,3,4],5)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


# tf.ones

In [16]:
ones_tensor = tf.ones([2,2,2])
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [17]:
ones_like = tf.ones_like(fill_tensor)
print(ones_like)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


In [18]:
zeros_tensor = tf.zeros([3,2])
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [19]:
print(tf.shape(tensor_three_d)) #returns a shape tensor of the input tensor

tf.Tensor([2 3 3], shape=(3,), dtype=int32)


In [20]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [21]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t, out_type = tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [22]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[102.14442   98.67352 ]
 [ 98.99159  100.5649  ]
 [ 99.78727   98.447014]], shape=(3, 2), dtype=float32)


In [23]:
tf.random.uniform(
    [5,5],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[18.24832  , 84.810745 , 52.031136 , 45.044647 , 22.933924 ],
       [ 2.9791713, 24.779547 , 33.391808 ,  6.7975044, 42.354774 ],
       [56.021523 , 55.80951  , 24.115395 ,  6.5324783, 89.74932  ],
       [87.80998  , 23.832916 , 81.92289  , 17.459465 , 55.591415 ],
       [22.824574 , 19.460308 , 71.55453  , 54.8414   , 42.35177  ]],
      dtype=float32)>

# tensor indexing

In [24]:
tensor_indexed = tf.constant([99,10,9,92,6,4,34,62,56])
print(tensor_indexed[0:4])
print(tensor_indexed[1:6])
print(tensor_indexed[1:6:2])

tf.Tensor([99 10  9 92], shape=(4,), dtype=int32)
tf.Tensor([10  9 92  6  4], shape=(5,), dtype=int32)
tf.Tensor([10 92  4], shape=(3,), dtype=int32)


In [25]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

# Indexing Dim. > 2

In [26]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]])

print(tensor_two_d[0:3,0:2]) #for rows, for columns
print(tensor_two_d[0:3,:]) # all columns
print(tensor_two_d[2]) #the whole of the third row
print(tensor_two_d[:,1])
print(tensor_two_d[...,1]) #all rows of the 2nd column 

tf.Tensor(
[[1 2]
 [2 3]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)
tf.Tensor([5 6 7], shape=(3,), dtype=int32)
tf.Tensor([2 3 6], shape=(3,), dtype=int32)
tf.Tensor([2 3 6], shape=(3,), dtype=int32)


In [27]:
tensor_three_d = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])

print(tensor_three_d[0,:,:])
print(tensor_three_d[0,0,:])
print(tensor_three_d[0,:,-1])
print(tensor_three_d[0:2,:,-1])
print(tensor_three_d[...,:,1])



tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([3 4 7], shape=(3,), dtype=int32)
tf.Tensor(
[[3 4 7]
 [3 4 7]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 3 6]
 [2 3 6]], shape=(2, 3), dtype=int32)


# Math Operations

In [28]:
x = tf.constant([-2.25, 3.25])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [29]:
# complex number
x_abs_complex = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [30]:
x = tf.constant([1, 2], dtype=tf.int8)
y = tf.constant([3, 0], dtype=tf.int8)
print(tf.add(x,y))
print(tf.multiply(x,y))
print(tf.subtract(x,y))
print(tf.math.divide_no_nan(x,y)) #gives 0. when divide by 0

tf.Tensor([4 2], shape=(2,), dtype=int8)
tf.Tensor([3 0], shape=(2,), dtype=int8)
tf.Tensor([-2  2], shape=(2,), dtype=int8)
tf.Tensor([0.33333334 0.        ], shape=(2,), dtype=float32)


In [31]:
x2 = tf.constant([[1, 2], [3,4]], dtype=tf.int8)
x3 = x2 = tf.constant([1, 2], dtype=tf.int8)
y2 = tf.constant([3], dtype=tf.int8) #this tensor is broadcasted
y3 = tf.constant([[3], [6], [9]], dtype=tf.int8)
print(tf.add(x2,y2))
print(tf.math.multiply(x2, y3))

tf.Tensor([4 5], shape=(2,), dtype=int8)
tf.Tensor(
[[ 3  6]
 [ 6 12]
 [ 9 18]], shape=(3, 2), dtype=int8)


In [32]:
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-2., 0., 2., 5.])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [33]:
x_argmax1 = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
print(x_argmax1.shape)
print(tf.math.argmax(x_argmax1, 0)) #returns the index of the maximum value in a row
#comparision is done on each row for the same column
print(tf.math.argmin(x_argmax1, 1))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [34]:
x_argmax2 = tf.constant([2, 20, 30, 3, 6])
print(tf.math.argmax(x_argmax2))


tf.Tensor(2, shape=(), dtype=int64)


In [35]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [36]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [37]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]], dtype = tf.float16)
print(tf.math.reduce_sum(tensor_two_d, axis=None, keepdims=False, name=None)) #summing all the elements in the tensor
print(tf.math.reduce_sum(tensor_two_d, axis=0, keepdims=False, name=None)) #fix the row and add the columns
print(tf.math.reduce_mean(tensor_two_d, axis=0, keepdims=False, name=None))
print(tf.math.reduce_std(tensor_two_d, axis=0, keepdims=True, name=None))

tf.Tensor(33.0, shape=(), dtype=float16)
tf.Tensor([ 8. 11. 14.], shape=(3,), dtype=float16)
tf.Tensor([2.666 3.666 4.668], shape=(3,), dtype=float16)
tf.Tensor([[1.7   1.7   1.699]], shape=(1, 3), dtype=float16)


In [38]:
tf.math.top_k(tensor_two_d) #first part 

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=float16, numpy=
array([[3.],
       [4.],
       [7.]], dtype=float16)>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [2],
       [2]], dtype=int32)>)

# Linear Algebra operations

In [39]:
x_1 = tf.constant([[1,2,0], [3,5,-1]])
x_2 = tf.constant([[3,4],[7,2],[9,2]]) 

tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17,  8],
       [35, 20]], dtype=int32)>

In [40]:
print(x_1@x_2) # '@' means matrix multiplication, '*' means element wise multiplication

tf.Tensor(
[[17  8]
 [35 20]], shape=(2, 2), dtype=int32)


In [41]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  5],
       [ 0, -1]], dtype=int32)>

In [42]:
x_1 = tf.constant([[[1,2],
                    [2,3]],

                    [[4,5],
                    [6,8]],

                    [[1,2],
                    [2,3]]
                    ])

x_2 = tf.constant([[[1,2],
                    [2,3]],

                    [[1,2],
                    [2,3]],

                    [[4,5],
                     [6,8]]])
print(x_1.shape, x_2.shape)
print(tf.linalg.matmul(x_1, x_2))

(3, 2, 2) (3, 2, 2)
tf.Tensor(
[[[ 5  8]
  [ 8 13]]

 [[14 23]
  [22 36]]

 [[16 21]
  [26 34]]], shape=(3, 2, 2), dtype=int32)


In [46]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]], dtype = tf.int32)

print(tf.linalg.band_part( tensor_two_d, 0, -1, name=None))

tf.Tensor(
[[1 2 3]
 [0 3 4]
 [0 0 7]], shape=(3, 3), dtype=int32)


In [54]:
tensor_two_d_inv = tf.constant([[1,2,3],
                            [2,3,4],
                            [5,6,7]], dtype = tf.float32)
tf.linalg.inv(tensor_two_d_inv) #inverse only works for square matrices

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ -6291460. ,   8388611. ,  -2097152. ],
       [ 12582914. , -16777218. ,   4194304. ],
       [ -6291455.5,   8388608. ,  -2097152. ]], dtype=float32)>

In [56]:
tensor_two_d_inv = tf.constant([[1,2,3],
                            [2,3,4],
                            [5,6,7]], dtype = tf.int32)
tensor_two_d@tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[20, 26, 32],
       [28, 37, 46],
       [52, 70, 88]], dtype=int32)>

In [58]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]], dtype = tf.float32)
s,u,v = tf.linalg.svd(tensor_two_d)
print(s)
print(u)
print(v)

tf.Tensor([1.2327755e+01 1.0131612e+00 2.0643913e-07], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.29715562 -0.7520271  -0.5883485 ]
 [ 0.43532172 -0.44171327  0.7844646 ]
 [ 0.84982     0.4892288  -0.1961161 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.43940678  0.80015934  0.40824848]
 [ 0.5677593   0.10479952 -0.81649655]
 [ 0.69611144 -0.590561    0.4082481 ]], shape=(3, 3), dtype=float32)


# EinSum Operator

In [59]:
A = np.array([[2,6,5,2], 
              [9,6,4,0],
              [4,7,4,8]])

B = np.array([[2,9,0,3,0],
              [4,5,2,1,4],
              [1,2,5,6,3],
              [5,7,3,5,2]])

print(A.shape, B.shape)
print(np.einsum('ij,jk -> ik', A,B))

(3, 4) (4, 5)
[[ 43  72  43  52  43]
 [ 46 119  32  57  36]
 [ 80 135  58  83  56]]


In [60]:
A = np.array([[2,6,5,2], 
              [9,6,4,0],
              [4,7,4,8]])

B = np.array([[2,9,0,3],
              [4,5,2,1],
              [1,2,5,6]])

print(A.shape, B.shape)
print(np.einsum('ij,ij -> ij', A,B)) #matrix element wise multiplication

(3, 4) (3, 4)
[[ 4 54  0  6]
 [36 30  8  0]
 [ 4 14 20 48]]


In [62]:
A = np.array([[2,6,5,2], 
              [9,6,4,0],
              [4,7,4,8]])
print(np.einsum('ij -> ji', A)) #getting the transpose


[[2 9 4]
 [6 6 7]
 [5 4 4]
 [2 0 8]]


In [ ]:
A = tf.constant([[[1,2,3],
                [2,3,4],
                [5,6,7]],

                [[1,2,3],
                [2,3,4],
                [5,6,7]]])

B = tf.constant([[[1,2,3],
                [2,3,4],
                [5,6,7]],

                [[1,2,3],
                [2,3,4],
                [5,6,7]]])

print(np.einsum('bij,bjk -> bik', A,B)) # this is matrix multiplication

[[[20 26 32]
  [28 37 46]
  [52 70 88]]

 [[20 26 32]
  [28 37 46]
  [52 70 88]]]


In [75]:
A = tf.constant([[[1,2,3],
                [2,3,4],
                [5,6,7]],

                [[1,2,3],
                [2,3,4],
                [5,6,7]]])

print(np.sum(A))
print(np.einsum('bij ->', A)) # no output mean that we are summing up all the possible values

66
66


In [78]:
A = np.array([[2,6,5,2], 
              [9,6,4,0],
              [4,7,4,8]])
print(np.sum(A, axis = 1)) # sum across columns
print(np.einsum('ij->j', A))
print('_______')
print(np.einsum('ij->i', A))


[15 19 23]
[15 19 13 10]
_______
[15 19 23]


# In the paper 'Attention is all you need'

In [ ]:
Q = np.random.randn(32,64,512) #bqm
K = np.random.randn(32,128,512) #bkm

print(np.einsum('bqm, bkm -> bqk', Q,K))
print(np.einsum('bqm, bkm -> bqk', Q,K).shape)

[[[-24.97088166   1.69398954   9.93849076 ...  12.42984315   2.60587901
    22.62456812]
  [-20.9280859    7.01922594  33.99074376 ... -14.25063746  21.28663678
    12.85835916]
  [  6.5491914  -28.60766617  25.89770059 ... -22.37452173  -0.92057166
    11.16961335]
  ...
  [ 33.3990304  -43.3584289   30.19793572 ...  11.33381898  -3.45757061
     4.94638799]
  [ -6.66704644  18.89461125  -1.34952408 ... -13.49083738  24.3501958
   -21.36730189]
  [-10.20292216  -7.17975934  -5.20900273 ... -35.43037815  19.36454532
    47.70084852]]

 [[ 12.23910267  17.8933221   40.62597471 ...  -5.6556763   30.32557103
    -8.82917778]
  [ 17.14894556  17.37458903 -59.05224774 ... -24.49615245 -20.20082394
   -10.44115643]
  [-20.40728809  21.6020422   -3.66951391 ...   3.42444848   7.42823092
    -0.28640465]
  ...
  [  2.85931528  29.89060226  35.70811735 ...  -1.32782945  -9.41934509
    23.36962679]
  [-25.28791558 -46.85159304  43.27539273 ... -28.79851646 -16.34210894
   -15.44013813]
  [-35.1

# In the paper 'Reformer'

In [86]:
A = np.random.randn(2,4,4,2) #bcij
B = np.random.rand(2,4,4,1) #bcik
print(np.einsum('bcik,bcij -> bckj', B,A))


[[[[ 0.21548353 -1.38734298]]

  [[-0.56320314  0.70017478]]

  [[-0.48640304  0.05716597]]

  [[-1.00808162  2.51440896]]]


 [[[ 2.28520346  0.39824292]]

  [[ 0.29404755 -0.90145632]]

  [[-0.27838905 -0.51514753]]

  [[ 2.0371457   0.17080801]]]]


# Common Tensor functions

In [94]:
tf.random.set_seed(42)
tensor_three_d = tf.random.uniform(
    shape=[4,2,3], 
    minval=0, 
    maxval=10, 
    dtype=tf.int32
)
print(tensor_three_d)

tf.Tensor(
[[[7 9 1]
  [6 2 4]]

 [[3 3 1]
  [1 2 0]]

 [[1 1 0]
  [8 9 2]]

 [[9 9 1]
  [2 7 4]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tf.expand_dims(tensor_three_d, axis = 0).shape) #added a dimension

(1, 4, 2, 3)


In [102]:
x = tf.constant([1,2,3])
print(x.shape)
print(tf.expand_dims(x, axis = 0)) #added a dimension, dim added to the 0th index
print(tf.expand_dims(x, axis = 1)) # dim added ot the 1st index

(3,)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
