In [1]:
import tensorflow as tf

# Tensor Dimensions

In [2]:
tensor_zero_d = tf.constant(4) #0 d tensor
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-1], dtype = tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.int64)
bool_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)
print(bool_tensor_one_d)

tf.Tensor([ 2.  0. -1.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -1], shape=(3,), dtype=int64)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [ ]:
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [5]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [6]:
tensor_three_d = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])
print(tensor_three_d.shape)
tensor_three_d_2 = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])
print(tensor_three_d_2.ndim)

(2, 3, 3)
3


In [7]:
print(tensor_three_d.ndim) # Dimension of our tensor

3


# 4D Tensor are 3D tensors stacked 

In [8]:
tensor_four_d = tf.constant([[[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]]
                             ,
                             [[[15,24,35],
                             [25,33,41],
                             [45,66,73]],

                             [[16,26,37],
                             [28,39,40],
                             [54,65,78]]]
                             ])
print(tensor_four_d.ndim)
print(tensor_four_d.shape)

4
(2, 2, 3, 3)


In [9]:
tf_string = tf.constant(['hello world', 'hi'])

## Convert a numpy array to a tensor

In [10]:
import numpy as np
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [11]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


## Eye Tensor

In [12]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=[2,2],
    dtype=tf.dtypes.int32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]


 [[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]], shape=(2, 2, 3, 3), dtype=int32)


In [13]:
print(3 * eye_tensor)

tf.Tensor(
[[[[3 0 0]
   [0 3 0]
   [0 0 3]]

  [[3 0 0]
   [0 3 0]
   [0 0 3]]]


 [[[3 0 0]
   [0 3 0]
   [0 0 3]]

  [[3 0 0]
   [0 3 0]
   [0 0 3]]]], shape=(2, 2, 3, 3), dtype=int32)


## tf.fill

In [14]:
fill_tensor = tf.fill([2,3,4],5)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


# tf.ones

In [15]:
ones_tensor = tf.ones([2,2,2])
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [ ]:
ones_like = tf.ones_like(fill_tensor)
print(ones_like)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


In [17]:
zeros_tensor = tf.zeros([3,2])
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [ ]:
print(tf.shape(tensor_three_d)) #returns a shape tensor of the input tensor

tf.Tensor([2 3 3], shape=(3,), dtype=int32)


In [19]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [20]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t, out_type = tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [21]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 99.88945   98.808556]
 [ 98.750015 100.82608 ]
 [101.417145 100.05336 ]], shape=(3, 2), dtype=float32)


In [22]:
tf.random.uniform(
    [5,5],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[91.18247 , 33.977425, 25.823807, 56.93196 , 47.23413 ],
       [13.754499, 50.229393, 46.280624, 14.036536, 72.208336],
       [24.161602, 81.27172 , 63.53109 , 93.56077 , 12.582981],
       [99.23897 , 37.377705, 61.57291 , 53.6458  , 59.321033],
       [11.57037 , 75.390854, 53.904247, 84.56724 , 64.45082 ]],
      dtype=float32)>

# tensor indexing

In [23]:
tensor_indexed = tf.constant([99,10,9,92,6,4,34,62,56])
print(tensor_indexed[0:4])
print(tensor_indexed[1:6])
print(tensor_indexed[1:6:2])

tf.Tensor([99 10  9 92], shape=(4,), dtype=int32)
tf.Tensor([10  9 92  6  4], shape=(5,), dtype=int32)
tf.Tensor([10 92  4], shape=(3,), dtype=int32)


In [24]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

# Indexing Dim. > 2

In [25]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]])

print(tensor_two_d[0:3,0:2]) #for rows, for columns
print(tensor_two_d[0:3,:]) # all columns
print(tensor_two_d[2]) #the whole of the third row
print(tensor_two_d[:,1])
print(tensor_two_d[...,1]) #all rows of the 2nd column 

tf.Tensor(
[[1 2]
 [2 3]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)
tf.Tensor([5 6 7], shape=(3,), dtype=int32)
tf.Tensor([2 3 6], shape=(3,), dtype=int32)
tf.Tensor([2 3 6], shape=(3,), dtype=int32)


In [26]:
tensor_three_d = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])

print(tensor_three_d[0,:,:])
print(tensor_three_d[0,0,:])
print(tensor_three_d[0,:,-1])
print(tensor_three_d[0:2,:,-1])
print(tensor_three_d[...,:,1])



tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([3 4 7], shape=(3,), dtype=int32)
tf.Tensor(
[[3 4 7]
 [3 4 7]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 3 6]
 [2 3 6]], shape=(2, 3), dtype=int32)


# Math Operations

In [27]:
x = tf.constant([-2.25, 3.25])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [28]:
# complex number
x_abs_complex = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [29]:
x = tf.constant([1, 2], dtype=tf.int8)
y = tf.constant([3, 0], dtype=tf.int8)
print(tf.add(x,y))
print(tf.multiply(x,y))
print(tf.subtract(x,y))
print(tf.math.divide_no_nan(x,y)) #gives 0. when divide by 0

tf.Tensor([4 2], shape=(2,), dtype=int8)
tf.Tensor([3 0], shape=(2,), dtype=int8)
tf.Tensor([-2  2], shape=(2,), dtype=int8)
tf.Tensor([0.33333334 0.        ], shape=(2,), dtype=float32)


In [30]:
x2 = tf.constant([[1, 2], [3,4]], dtype=tf.int8)
x3 = x2 = tf.constant([1, 2], dtype=tf.int8)
y2 = tf.constant([3], dtype=tf.int8) #this tensor is broadcasted
y3 = tf.constant([[3], [6], [9]], dtype=tf.int8)
print(tf.add(x2,y2))
print(tf.math.multiply(x2, y3))

tf.Tensor([4 5], shape=(2,), dtype=int8)
tf.Tensor(
[[ 3  6]
 [ 6 12]
 [ 9 18]], shape=(3, 2), dtype=int8)


In [31]:
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-2., 0., 2., 5.])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [40]:
x_argmax1 = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
print(x_argmax1.shape)
print(tf.math.argmax(x_argmax1, 0)) #returns the index of the maximum value in a row
#comparision is done on each row for the same column
print(tf.math.argmin(x_argmax1, 1))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [35]:
x_argmax2 = tf.constant([2, 20, 30, 3, 6])
print(tf.math.argmax(x_argmax2))


tf.Tensor(2, shape=(), dtype=int64)


In [41]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [42]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [54]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]], dtype = tf.float16)
print(tf.math.reduce_sum(tensor_two_d, axis=None, keepdims=False, name=None)) #summing all the elements in the tensor
print(tf.math.reduce_sum(tensor_two_d, axis=0, keepdims=False, name=None)) #fix the row and add the columns
print(tf.math.reduce_mean(tensor_two_d, axis=0, keepdims=False, name=None))
print(tf.math.reduce_std(tensor_two_d, axis=0, keepdims=True, name=None))

tf.Tensor(33.0, shape=(), dtype=float16)
tf.Tensor([ 8. 11. 14.], shape=(3,), dtype=float16)
tf.Tensor([2.666 3.666 4.668], shape=(3,), dtype=float16)
tf.Tensor([[1.7   1.7   1.699]], shape=(1, 3), dtype=float16)


In [ ]:
tf.math.top_k(tensor_two_d) #first part 

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=float16, numpy=
array([[3.],
       [4.],
       [7.]], dtype=float16)>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [2],
       [2]], dtype=int32)>)