In [3]:
import tensorflow as tf

# Tensor Dimensions

In [4]:
tensor_zero_d = tf.constant(4) #0 d tensor
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
tensor_one_d = tf.constant([2,0,-1], dtype = tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.int64)
bool_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)
print(bool_tensor_one_d)

tf.Tensor([ 2.  0. -1.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -1], shape=(3,), dtype=int64)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [6]:
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [7]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [8]:
tensor_three_d = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])
print(tensor_three_d.shape)
tensor_three_d_2 = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])
print(tensor_three_d_2.ndim)

(2, 3, 3)
3


In [9]:
print(tensor_three_d.ndim) # Dimension of our tensor

3


# 4D Tensor are 3D tensors stacked 

In [10]:
tensor_four_d = tf.constant([[[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]]
                             ,
                             [[[15,24,35],
                             [25,33,41],
                             [45,66,73]],

                             [[16,26,37],
                             [28,39,40],
                             [54,65,78]]]
                             ])
print(tensor_four_d.ndim)
print(tensor_four_d.shape)

4
(2, 2, 3, 3)


In [11]:
tf_string = tf.constant(['hello world', 'hi'])

## Convert a numpy array to a tensor

In [12]:
import numpy as np
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [13]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


## Eye Tensor

In [19]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=[2,2],
    dtype=tf.dtypes.int32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]


 [[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]], shape=(2, 2, 3, 3), dtype=int32)


In [18]:
print(3 * eye_tensor)

tf.Tensor(
[[[3 0 0]
  [0 3 0]
  [0 0 3]]

 [[3 0 0]
  [0 3 0]
  [0 0 3]]], shape=(2, 3, 3), dtype=int32)


## tf.fill

In [30]:
fill_tensor = tf.fill([2,3,4],5)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


# tf.ones

In [31]:
ones_tensor = tf.ones([2,2,2])
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [32]:
ones_like = tf.ones_like(fill_tensor)
print(ones_like)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


In [33]:
zeros_tensor = tf.zeros([3,2])
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [ ]:
print(tf.shape(tensor_three_d)) #returns a shape tensor of the input tensor

tf.Tensor([2 3 3], shape=(3,), dtype=int32)


In [35]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [38]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t, out_type = tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [47]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[100.86096 100.91938]
 [100.14827 100.39264]
 [ 98.10667 100.91285]], shape=(3, 2), dtype=float32)


In [51]:
tf.random.uniform(
    [5,5],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[25.114368 , 34.022556 , 94.64272  ,  0.3783822, 61.26157  ],
       [37.45154  , 14.041174 , 73.24858  , 56.106102 , 44.01345  ],
       [ 2.1712065, 80.30788  ,  2.3268938,  9.819889 , 43.10484  ],
       [70.46026  , 56.403625 , 63.55556  , 42.1744   , 31.379747 ],
       [47.741116 , 99.636284 , 29.682482 , 39.45906  , 44.74696  ]],
      dtype=float32)>

# tensor indexing

In [57]:
tensor_indexed = tf.constant([99,10,9,92,6,4,34,62,56])
print(tensor_indexed[0:4])
print(tensor_indexed[1:6])
print(tensor_indexed[1:6:2])

tf.Tensor([99 10  9 92], shape=(4,), dtype=int32)
tf.Tensor([10  9 92  6  4], shape=(5,), dtype=int32)
tf.Tensor([10 92  4], shape=(3,), dtype=int32)


In [55]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

# Indexing Dim. > 2

In [65]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]])

print(tensor_two_d[0:3,0:2]) #for rows, for columns
print(tensor_two_d[0:3,:]) # all columns
print(tensor_two_d[2]) #the whole of the third row
print(tensor_two_d[:,1])
print(tensor_two_d[...,1]) #all rows of the 2nd column 

tf.Tensor(
[[1 2]
 [2 3]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)
tf.Tensor([5 6 7], shape=(3,), dtype=int32)
tf.Tensor([2 3 6], shape=(3,), dtype=int32)
tf.Tensor([2 3 6], shape=(3,), dtype=int32)


In [75]:
tensor_three_d = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])

print(tensor_three_d[0,:,:])
print(tensor_three_d[0,0,:])
print(tensor_three_d[0,:,-1])
print(tensor_three_d[0:2,:,-1])
print(tensor_three_d[...,:,1])



tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([3 4 7], shape=(3,), dtype=int32)
tf.Tensor(
[[3 4 7]
 [3 4 7]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 3 6]
 [2 3 6]], shape=(2, 3), dtype=int32)
