In [1]:
import tensorflow as tf


# Tensor Dimensions

In [4]:
tensor_zero_d = tf.constant(4) #0 d tensor
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [26]:
tensor_one_d = tf.constant([2,0,-1], dtype = tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.int64)
bool_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)
print(bool_tensor_one_d)

tf.Tensor([ 2.  0. -1.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -1], shape=(3,), dtype=int64)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [28]:
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [10]:
tensor_two_d = tf.constant([[1,2,3],
                             [2,3,4],
                             [5,6,7]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [15]:
tensor_three_d = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])
print(tensor_three_d.shape)
tensor_three_d_2 = tf.constant([[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]])
print(tensor_three_d_2.ndim)

(2, 3, 3)
3


In [14]:
print(tensor_three_d.ndim) # Dimension of our tensor

3


# 4D Tensor are 3D tensors stacked 

In [19]:
tensor_four_d = tf.constant([[[[1,2,3],
                             [2,3,4],
                             [5,6,7]],

                             [[1,2,3],
                             [2,3,4],
                             [5,6,7]]]
                             ,
                             [[[15,24,35],
                             [25,33,41],
                             [45,66,73]],

                             [[16,26,37],
                             [28,39,40],
                             [54,65,78]]]
                             ])
print(tensor_four_d.ndim)
print(tensor_four_d.shape)

4
(2, 2, 3, 3)


In [ ]:
tf_string = tf.constant(['hello world', 'hi'])

## Convert a numpy array to a tensor

In [30]:
import numpy as np
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [31]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


## Eye Tensor

In [37]:
eye_tensor = tf.eye(
    3,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.int32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]


 [[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]], shape=(2, 4, 3, 3), dtype=int32)


In [34]:
print(3 * eye_tensor)

tf.Tensor(
[[3 0 0]
 [0 3 0]
 [0 0 3]], shape=(3, 3), dtype=int32)


## tf.fill